apiVersion: "monitoring.coreos.com/v1"
kind: "PodMonitor"
metadata:
  name: "cilium-components"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  namespaceSelector:
    matchNames:
      - "kube-system"
  selector:
    matchLabels:
      app.kubernetes.io/part-of: "cilium"
  podMetricsEndpoints:
    - port: "prometheus"
      interval: "30s"
      honorLabels: true
