apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "ScrapeConfig"
metadata:
  name: "static-nodes"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  honorLabels: true
  scrapeInterval: "30s"
  staticConfigs:
    - labels:
        job: "testing"
      targets:
        - "192.168.56.10:9100"
