apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "general-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "general-record.rules"
      rules:
        - expr: 'count without(instance, pod, node) (up == 1)'
          record: 'count:up1'

        - expr: 'count without(instance, pod, node) (up == 0)'
          record: 'count:up0'

    - name: "general-alert.rules"
      rules:
        - alert: "TargetDown"
          expr: |
            100 * (count(up == 0) by (cluster, job, namespace, service) / count(up) by (cluster, job, namespace, service)) > 10
          for: "10m"
          labels:
            severity: "warning"
          annotations:
            summary: 'One or more targets are unreachable.'
            description: |
              {{ printf "%.4g" $value }}% of the {{ $labels.job }}/{{ $labels.service }} targets in {{ $labels.namespace }} namespace are down.
            runbook_url: 'https://runbooks.prometheus-operator.dev/runbooks/general/targetdown'

        - alert: "KubeVersionMismatch"
          expr: |
            count by (cluster) (
                count by (git_version, cluster) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"git_version","$1","git_version","(v[0-9]*.[0-9]*).*"))
            ) > 1
          for: "15m"
          labels:
            severity: "warning"
          annotations:
            summary: 'Different semantic versions of Kubernetes components running.'
            description: 'There are {{ $value }} different semantic versions of Kubernetes components running.'
            runbook_url: 'https://runbooks.prometheus-operator.dev/runbooks/kubernetes/kubeversionmismatch'
