{
 "title": "aws-network-lb",
 "tags": [
  "AWS",
  "Network"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   { "name": "nlb", "label": "NLB", "query": { "query": "label_values(load_balancer)" } }
  ]
 },
 "panels": [
  { "title": "NLB: ${nlb}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nlb" },
  {
   "title": "Active Flow (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_active_flow_count_average{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "New Flow (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_new_flow_count_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Active TCP Flow (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_active_flow_count_tcp_average{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "New TCP Flow (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_new_flow_count_tcp_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Port Allocation Errors (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_port_allocation_error_count_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Packets Peak per Second (Max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_peak_packets_per_second_maximum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Packets Processed (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_processed_packets_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "Bytes Processed (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_processed_bytes_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "TCP ELB Reset (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_tcp_elb_reset_count_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "TCP Bytes Processed (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_processed_bytes_tcp_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "TCP Client Reset (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_tcp_client_reset_count_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  },
  {
   "title": "TCP Target Reset (Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(aws_networkelb_tcp_target_reset_count_sum{load_balancer=~\"${nlb}\"}) by(availability_zone)",
     "legendFormat": "{{availability_zone}}"
    }
   ]
  }
 ]
}