{
 "title": "aws-rds-info",
 "tags": [
  "AWS",
  "DB"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(dbinstance_identifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "DB: ${database}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "database" },
  {
   "title": "CPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Burst balance (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(aws_rds_burst_balance_average{dbinstance_identifier=~\"${database}\"}) by(dbinstance_identifier)",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Free Storage Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_free_storage_space_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_swap_usage_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Read/Write Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "aws_rds_write_throughput_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Read/Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "aws_rds_write_iops_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network RX/TX Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "aws_rds_network_receive_throughput_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "RX"
    },
    {
     "expr": "aws_rds_network_transmit_throughput_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "aws_rds_disk_queue_depth_average{dbinstance_identifier=~\"${database}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  }
 ]
}