{
 "title": "Cilium Agent Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(cilium_version, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Errors & Warnings",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_errors_warnings_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (level) * 60",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "CPU Usage per node",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irate(cilium_process_cpu_seconds_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_process_cpu_seconds_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_process_cpu_seconds_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 100",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Generic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Virtual Memory Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(cilium_process_virtual_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "Min Virtual Memory"
    },
    {
     "expr": "avg(cilium_process_virtual_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "Average Virtual Memory"
    },
    {
     "expr": "max(cilium_process_virtual_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "Max Virtual Memory"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cilium_process_resident_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_process_resident_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_process_resident_memory_bytes{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_process_open_fds{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "all nodes"
    },
    {
     "expr": "min(cilium_process_open_fds{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "min/node"
    },
    {
     "expr": "avg(cilium_process_open_fds{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "avg/node"
    },
    {
     "expr": "max(cilium_process_open_fds{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "max/node"
    }
   ]
  },
  {
   "title": "System-wide BPF memory usage",
   "type": "timeseries",
   "description": "BPF memory usage in the entire system including components not managed by Cilium.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(\n  cilium_bpf_maps_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"} +\n  cilium_bpf_progs_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"}\n)",
     "legendFormat": "AVG_bpf_memory_bytes_avg"
    },
    {
     "expr": "max(\n  cilium_bpf_maps_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"} +\n  cilium_bpf_progs_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"}\n)",
     "legendFormat": "MAX_bpf_memory_bytes_max"
    },
    {
     "expr": "min(\n  cilium_bpf_maps_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"} +\n  cilium_bpf_progs_virtual_memory_max_bytes{container=\"cilium-agent\", pod=~\"$pod\"}\n)",
     "legendFormat": "MIN_bpf_memory_bytes_min"
    }
   ]
  },
  {
   "title": "BPF map pressure",
   "type": "timeseries",
   "description": "Fill percentage of BPF maps, tagged by map name",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(cilium_bpf_map_pressure{container=\"cilium-agent\", pod=~\"$pod\"}) by (map_name)",
     "legendFormat": "{{map_name}}"
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "API call latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(cilium_agent_api_process_time_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API call latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  rate(cilium_agent_api_process_time_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "API calls (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "API calls (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}} "
    }
   ]
  },
  {
   "title": "API return codes (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}})"
    }
   ]
  },
  {
   "title": "API return codes (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_agent_api_process_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, path, return_code)",
     "legendFormat": "{{return_code}} ({{method}} {{path}})"
    }
   ]
  },
  {
   "title": "Cilium",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {}
   ]
  },
  {
   "title": "BPF",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "System calls (average node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_bpf_syscall_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "System calls (max node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(cilium_bpf_syscall_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "System call latency (avg node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(cilium_bpf_syscall_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_bpf_syscall_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "System call latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  rate(cilium_bpf_syscall_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_bpf_syscall_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Map ops (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, avg(rate(cilium_bpf_map_ops_total{container=\"cilium-agent\", pod=~\"$pod\"}[5m])) by (map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "Map ops (max node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, max(rate(cilium_bpf_map_ops_total{container=\"cilium-agent\", pod=~\"$pod\"}[5m])) by (map_name, operation))",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "Map ops (sum failures)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_bpf_map_ops_total{container=\"cilium-agent\", outcome=\"fail\", pod=~\"$pod\"}[5m])) by (map_name, operation)",
     "legendFormat": "{{map_name}} {{operation}}"
    }
   ]
  },
  {
   "title": "kvstore",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(kvstore_operations_total{pod=~\"$pod\"}[1m])) by (scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "Operations (max node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(kvstore_operations_total{pod=~\"$pod\"}[1m])) by (scope, action)",
     "legendFormat": "{{scope}} {{action}}"
    }
   ]
  },
  {
   "title": "Latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5,\n  avg(rate(cilium_kvstore_operations_duration_seconds_sum{pod=~\"$pod\"}[1m])) by (action, scope) /\n  avg(rate(cilium_kvstore_operations_duration_seconds_count{pod=~\"$pod\"}[1m])) by (action, scope)\n)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5,\n  max(rate(cilium_kvstore_operations_duration_seconds_sum{pod=~\"$pod\"}[1m])) by (action, scope) /\n  avg(rate(cilium_kvstore_operations_duration_seconds_count{pod=~\"$pod\"}[1m])) by (action, scope)\n)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Events received (average node)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kvstore_events_queue_seconds_count{pod=~\"$pod\"}[1m])) by (scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Cilium network information",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Forwarded Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_count_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (direction)",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Forwarded Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_forward_bytes_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (direction) * 8",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv4\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv6\", protocol=\"TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv4 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv4\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "IPv6 Conntrack Non-TCP",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"alive\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "max"
    },
    {
     "expr": "avg(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted"
    },
    {
     "expr": "max(cilium_datapath_conntrack_gc_entries{container=\"cilium-agent\", status=\"deleted\", family=\"ipv6\", protocol=\"non-TCP\", pod=~\"$pod\"}) by (family, status)",
     "legendFormat": "deleted max"
    }
   ]
  },
  {
   "title": "Allocated Addresses",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_ip_addresses{container=\"cilium-agent\", pod=~\"$pod\"}) by (family)",
     "legendFormat": "{{family}}"
    }
   ]
  },
  {
   "title": "Datapath Conntrack Dump Resets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_datapath_conntrack_dump_resets_total{container=\"cilium-agent\", pod=~\"$pod\"}) by (area, family, name)",
     "legendFormat": "{{name}} {{area}} {{family}}"
    }
   ]
  },
  {
   "title": "Service Updates",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_services_events_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Connectivity Health",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_unreachable_nodes{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "unreachable nodes"
    },
    {
     "expr": "sum(cilium_unreachable_health_endpoints{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "unreachable health endpoints"
    }
   ]
  },
  {
   "title": "Dropped Egress Packets",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"EGRESS\", container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_nodes_all_events_received_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (event_type, source) * 60",
     "legendFormat": "{{eventType}} {{source}}"
    }
   ]
  },
  {
   "title": "Dropped Egress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"EGRESS\", container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cilium_nodes_all_num{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Average Nodes"
    },
    {
     "expr": "min(cilium_nodes_all_num{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Min Nodes"
    },
    {
     "expr": "max(cilium_nodes_all_num{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "Max Nodes"
    }
   ]
  },
  {
   "title": "Policy",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "L7 forwarded request",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_policy_l7_denied_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_forwarded_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "forwarded"
    },
    {
     "expr": "sum(rate(cilium_policy_l7_received_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Cilium drops Ingress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_count_total{direction=\"INGRESS\", container=\"cilium-agent\", pod=~\"$pod\"}[5m])) by (reason)",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Proxy response time (Avg)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope) /\nsum(rate(cilium_proxy_upstream_reply_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "{{scope}}"
    },
    {
     "expr": "avg(cilium_policy_l7_parse_errors_total{container=\"cilium-agent\", pod=~\"$pod\"})",
     "legendFormat": "parse errors"
    }
   ]
  },
  {
   "title": "Dropped Ingress Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_drop_bytes_total{direction=\"INGRESS\", container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (reason) * 8",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_call_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope) /\nsum(rate(cilium_triggers_policy_update_call_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_call_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope) /\nsum(rate(cilium_triggers_policy_update_call_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_call_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope) /\nsum(rate(cilium_triggers_policy_update_call_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Proxy response time (Max)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(rate(cilium_proxy_upstream_reply_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope) /\nsum(rate(cilium_proxy_upstream_reply_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "Max {{scope}}"
    },
    {
     "expr": "max(rate(cilium_policy_l7_parse_errors_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m]))",
     "legendFormat": "parse errors"
    }
   ]
  },
  {
   "title": "Endpoints policy enforcement status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_policy_endpoint_enforcement_status{container=\"cilium-agent\", pod=~\"$pod\"}) by (enforcement)",
     "legendFormat": "{{enforcement}}"
    }
   ]
  },
  {
   "title": "Policy Trigger Runs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "min(rate(cilium_triggers_policy_update_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 60",
     "legendFormat": "min trigger"
    },
    {
     "expr": "avg(rate(cilium_triggers_policy_update_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 60",
     "legendFormat": "average trigger"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 60",
     "legendFormat": "max trigger"
    },
    {
     "expr": "max(rate(cilium_triggers_policy_update_folds{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod) * 60",
     "legendFormat": "folds"
    }
   ]
  },
  {
   "title": "Proxy Redirects",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_proxy_redirects{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_proxy_redirects{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_proxy_redirects{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "DNS proxy requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_proxy_upstream_reply_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Policies Per Node",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy{container=\"cilium-agent\", pod=~\"$pod\"}) by(pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_policy{container=\"cilium-agent\", pod=~\"$pod\"}) by(pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_policy{container=\"cilium-agent\", pod=~\"$pod\"}) by(pod)",
     "legendFormat": "max"
    },
    {
     "expr": "sum(cilium_policy_import_errors_total{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "policy import errors"
    }
   ]
  },
  {
   "title": "Policy Revision",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(cilium_policy_max_revision{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "min"
    },
    {
     "expr": "avg(cilium_policy_max_revision{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "avg"
    },
    {
     "expr": "max(cilium_policy_max_revision{container=\"cilium-agent\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 147 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Endpoint regeneration time (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.90,\n  rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{container=\"cilium-agent\", scope!=\"total\", pod=~\"$pod\"}[5m])\n)) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regeneration time (99th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.99,\n  rate(cilium_endpoint_regeneration_time_stats_seconds_bucket{container=\"cilium-agent\", scope!=\"total\", pod=~\"$pod\"}[5m])\n)) by (scope)",
     "legendFormat": "{{scope}}"
    }
   ]
  },
  {
   "title": "Endpoint regenerations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_endpoint_regenerations_total{container=\"cilium-agent\", pod=~\"$pod\"}[30s])) by(outcome)",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "Cilium endpoint state",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(cilium_endpoint_state{container=\"cilium-agent\", pod=~\"$pod\"}) by (endpoint_state)",
     "legendFormat": "{{endpoint_state}}"
    }
   ]
  },
  {
   "title": "Controllers",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 162 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Controllers",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod)",
     "legendFormat": "Runs"
    },
    {
     "expr": "sum(cilium_controllers_failing{container=\"cilium-agent\", pod=~\"$pod\"}) by(pod)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Controller Durations",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_controllers_runs_duration_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod, status) /\nsum(rate(cilium_controllers_runs_duration_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (pod, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Kubernetes integration",
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "targets": [
    {}
   ]
  },
  {
   "title": "apiserver latency (average node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(\n  rate(cilium_k8s_client_api_latency_time_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_k8s_client_api_latency_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver latency (max node)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n  rate(cilium_k8s_client_api_latency_time_seconds_sum{container=\"cilium-agent\", pod=~\"$pod\"}[1m]) /\n  rate(cilium_k8s_client_api_latency_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])\n) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_latency_time_seconds_count{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, path)",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "apiserver calls (sum all nodes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_k8s_client_api_calls_total{container=\"cilium-agent\", pod=~\"$pod\"}[1m])) by (method, return_code)",
     "legendFormat": "{{method}} {{return_code}}"
    }
   ]
  },
  {
   "title": "Valid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{container=\"cilium-agent\", equal=\"true\", valid=\"true\", pod=~\"$pod\"}[5m])) by (scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Unnecessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 184 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{container=\"cilium-agent\", equal=\"true\", valid=\"false\", pod=~\"$pod\"}[5m])) by (scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Valid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{container=\"cilium-agent\", equal=\"false\", valid=\"true\", pod=~\"$pod\"}[5m])) by (scope, action, valid)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "Invalid, Necessary K8s Events Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(cilium_kubernetes_events_received_total{container=\"cilium-agent\", equal=\"false\", valid=\"false\", pod=~\"$pod\"}[5m])) by (scope, action)",
     "legendFormat": "{{action}} {{scope}}"
    }
   ]
  },
  {
   "title": "CiliumNetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"CiliumNetworkPolicy\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "NetworkPolicy Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"NetworkPolicy\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Pod Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"Pod\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Node Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"Node\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}} avg"
    }
   ]
  },
  {
   "title": "Service Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"Service\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Endpoints Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 212 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"Endpoint\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Namespace Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_kubernetes_events_total{container=\"cilium-agent\", scope=\"Namespace\", pod=~\"$pod\"}[1m])) by (action) * 60",
     "legendFormat": "{{action}}"
    }
   ]
  }
 ]
}