{
 "title": "Cilium Operator Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "min(irate(cilium_operator_process_cpu_seconds_total{container=\"cilium-operator\"}[1m])) by (container) * 100",
     "legendFormat": "min"
    },
    {
     "expr": "avg(irate(cilium_operator_process_cpu_seconds_total{container=\"cilium-operator\"}[1m])) by (container) * 100",
     "legendFormat": "avg"
    },
    {
     "expr": "max(irate(cilium_operator_process_cpu_seconds_total{container=\"cilium-operator\"}[1m])) by (container) * 100",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Resident memory status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cilium_operator_process_resident_memory_bytes{container=\"cilium-operator\"})",
     "legendFormat": "AVG_resident_memory_bytes"
    },
    {
     "expr": "max(cilium_operator_process_resident_memory_bytes{container=\"cilium-operator\"})",
     "legendFormat": "MAX_resident_memory_bytes_max"
    },
    {
     "expr": "min(cilium_operator_process_resident_memory_bytes{container=\"cilium-operator\"})",
     "legendFormat": "MIN_resident_memory_bytes_min"
    }
   ]
  },
  {
   "title": "IPAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "IP Addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(cilium_operator_ipam_ips) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "EC2 API Interactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(cilium_operator_ec2_api_duration_seconds_sum[1m])/rate(cilium_operator_ec2_api_duration_seconds_count[1m])",
     "legendFormat": "{{operation}} {{response_code}}"
    }
   ]
  },
  {
   "title": "Number of nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "cilium_operator_ipam_nodes", "legendFormat": "{{category}}" }
   ]
  },
  {
   "title": "Interfaces with addresses available",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "cilium_operator_ipam_available", "legendFormat": "interfaces" }
   ]
  },
  {
   "title": "Metadata Resync Operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(cilium_operator_ipam_resync_total[1m])",
     "legendFormat": "operations"
    }
   ]
  },
  {
   "title": "EC2 client side rate limiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(cilium_operator_ec2_api_rate_limit_duration_seconds_sum[1m])/rate(cilium_operator_ec2_api_rate_limit_duration_seconds_count[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Interface Creation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(cilium_operator_ipam_interface_creation_ops[1m])) by (subnetId, status)",
     "legendFormat": "{{status}} ({{subnetId}})"
    }
   ]
  }
 ]
}