{
 "title": "k8s-pod-info",
 "tags": [ "testing" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pods",
    "query": {
     "query": "label_values(kube_pod_created{namespace=\"$ns\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "${ns}/${pod}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "CPU time consumed in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "Usage: {{container}}"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"${ns}\", pod=~\"${pod}\", resource=\"cpu\"}) by(container)",
     "legendFormat": "Limit: {{container}}"
    }
   ]
  },
  {
   "title": "Current memory usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of OOM events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_oom_events_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of memory usage hits limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_memory_failcnt{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of processes running inside the container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_processes{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory allocation failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_memory_failures_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of threads running inside the container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_threads{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Number of open sockets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(container_sockets{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of FS reads bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of network RX/TX bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Count of FS writes bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of network RX/TX packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Count of FS reads completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of network RX/TX errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_errors_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(irate(container_network_transmit_errors_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Count of FS writes completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_writes_total{namespace=~\"${ns}\", pod=~\"${pod}\", container!=\"\"}[$__rate_interval])) by(container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Count of network RX/TX packets dropped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_packets_dropped_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(irate(container_network_transmit_packets_dropped_total{namespace=~\"${ns}\", pod=~\"${pod}\"}[$__rate_interval]))",
     "legendFormat": "TX"
    }
   ]
  }
 ]
}