{
 "title": "Karpenter Pools",
 "tags": [
  "karpenter",
  "k8s"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   { "name": "pool", "label": "Pool", "query": { "query": "label_values(nodepool)" } }
  ]
 },
 "panels": [
  { "title": "Karpenter summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cloud Provider errors per 15m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(karpenter_cloudprovider_errors_total[15m])) by(error)",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Total cluster nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_cluster_state_node_count)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Problem with registering new nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodeclaims_launched) by(nodepool) - sum(karpenter_nodeclaims_registered) by(nodepool) > 0",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  {
   "title": "Pods per node pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool!=\"\"}) by(nodepool) > 0",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  { "title": "Node pool summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Created nodes per node pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_created) by(nodepool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Terminated nodes per node pool",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_terminated) by(nodepool)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per pool (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor((\n    sum(karpenter_nodepool_usage{resource_type=\"cpu\"}) by(nodepool)\n    / sum(karpenter_nodepool_limit{resource_type=\"cpu\"}) by(nodepool))\n* 100)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  {
   "title": "Memory usage per pool (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor((\n    sum(karpenter_nodepool_usage{resource_type=\"memory\"}) by(nodepool)\n    / sum(karpenter_nodepool_limit{resource_type=\"memory\"}) by(nodepool))\n* 100)",
     "legendFormat": "{{nodepool}}"
    }
   ]
  },
  { "title": "Node pool usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "CPU usage per node (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor((\n    sum(karpenter_nodes_total_pod_requests{nodepool=~\"${pool}\",resource_type=\"cpu\"}) by(nodepool,node_name)\n    / sum(karpenter_nodes_total_pod_limits{nodepool=~\"${pool}\",resource_type=\"cpu\"}) by(nodepool,node_name)\n) * 100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory usage per node (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "floor((\n    sum(karpenter_nodes_total_pod_requests{nodepool=~\"${pool}\",resource_type=\"memory\"}) by(nodepool,node_name)\n    / sum(karpenter_nodes_total_pod_limits{nodepool=~\"${pool}\",resource_type=\"memory\"}) by(nodepool,node_name)\n) * 100)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "CPU overhead per node (?)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_system_overhead{nodepool=~\"${pool}\",resource_type=\"cpu\"}) by(nodepool,node_name) > 0",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Memory overhead per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_system_overhead{nodepool=~\"${pool}\",resource_type=\"memory\"}) by(nodepool,node_name) > 0",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Storage overhead per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(karpenter_nodes_system_overhead{nodepool=~\"${pool}\",resource_type=\"ephemeral_storage\"}) by(nodepool,node_name) > 0",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Pods per node",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(karpenter_pods_state{nodepool=~\"${pool}\"}) by(nodepool,node)",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}