{
 "title": "kube-log-generator",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(uptime_seconds{service=\"log-generator-api\"}) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(irate(loggen_events_total{service=\"log-generator-api\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "sum(irate(loggen_events_total{service=\"log-generator-api\"}[$__rate_interval]))",
     "legendFormat": "SUM"
    }
   ]
  },
  {
   "title": "Total bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(irate(loggen_event_bytes_total{service=\"log-generator-api\"}[$__rate_interval]))",
     "legendFormat": "AVG"
    },
    {
     "expr": "sum(irate(loggen_event_bytes_total{service=\"log-generator-api\"}[$__rate_interval]))",
     "legendFormat": "SUM"
    }
   ]
  }
 ]
}