{
 "title": "Loki components v2",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   { "name": "ns", "query": "monitoring" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of log messages created by Loki itself",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_internal_log_messages_total[2m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(loki_internal_log_messages_total{level=\"error\"}[2m]))",
     "legendFormat": "Errors"
    },
    {
     "expr": "sum(rate(loki_internal_log_messages_total{level=\"warn\"}[2m]))",
     "legendFormat": "Warnings"
    }
   ]
  },
  {
   "title": "Storage download operation (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(loki_tsdb_shipper_tables_download_operation_duration_seconds[5m])) by(component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage upload operations (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(loki_tsdb_shipper_tables_upload_operation_total{status=\"success\"}[5m]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(loki_tsdb_shipper_tables_upload_operation_total{status=\"failure\"}[5m]))",
     "legendFormat": "Failure"
    }
   ]
  },
  {
   "title": "Storage sync operations (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(loki_tsdb_shipper_tables_sync_operation_total{status=\"failure\"}[5m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(increase(loki_tsdb_shipper_tables_sync_operation_total{status=\"success\"}[5m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Loki - Distributors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-distributor-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-distributor-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The total number of uncompressed bytes received per both tenant and retention hours",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of log entries received per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of batch appends sent to ingesters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_appends_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of failed batch appends sent to ingesters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki - Ingesters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-ingester-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-ingester-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The total number of chunks in memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_ingester_memory_chunks)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of streams in memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_ingester_memory_streams)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total bytes stored in chunks per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of streams created per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_streams_created_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Total stored chunks per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_stored_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of streams removed per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_streams_removed_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of series pending in the flush queue",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cortex_ingester_flush_queue_length)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of chunks created in the ingester",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_created_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki - Querier",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-querier-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-querier-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The current number of clients connected to query-frontend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_query_frontend_clients)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of active tailers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "sum(loki_querier_tail_active)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Number of concurrent querier workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_worker_concurrency)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of active streams being tailed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_tail_active_streams)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of queries being processed by the querier workers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_worker_inflight_queries)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of active streams being tailed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(loki_querier_tail_bytes_total)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of index cache corruptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_index_cache_corruptions_total)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of index cache operations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_querier_index_cache_gets_total)",
       "legendFormat": "gets"
      },
      {
       "expr": "sum(loki_querier_index_cache_hits_total)",
       "legendFormat": "hits"
      },
      {
       "expr": "sum(loki_querier_index_cache_puts_total)",
       "legendFormat": "puts"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki - Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-frontend-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-frontend-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The current number of queues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_query_frontend_enqueue_count)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The current number of shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_query_frontend_shards_total)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki - Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-scheduler-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-scheduler-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The current number of frontend clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cortex_query_scheduler_connected_frontend_clients{container=\"query-scheduler\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "DNS requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cortex_dns_lookups_total{container=\"query-scheduler\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "cortex_dns_failures_total{container=\"query-scheduler\"}",
       "legendFormat": "Failure"
      }
     ]
    },
    {
     "title": "The current number of querier clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "cortex_query_scheduler_connected_querier_clients{container=\"query-scheduler\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The current number of inflight requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(cortex_query_scheduler_inflight_requests{container=\"query-scheduler\"})",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  {
   "title": "Promtail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of bytes read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "sum(promtail_read_bytes_total)", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Number of bytes sent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(promtail_sent_bytes_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of bytes dropped because failed to be sent to the ingester after all retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(promtail_dropped_bytes_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of lines read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(promtail_read_lines_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of log entries dropped because failed to be sent to the ingester after all retries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(promtail_dropped_entries_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of active files",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(promtail_files_active_total)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of total failed targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(promtail_targets_failed_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Number of total active targets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(promtail_targets_active_total)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  }
 ]
}