{
 "title": "loki-logs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "loki" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   },
   {
    "name": "name",
    "label": "Name",
    "query": {}
   },
   {
    "name": "component",
    "label": "Component",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Logs - Sum per 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate({namespace=~\"${namespace}\", app_kubernetes_io_name=~\"${name}\", app_kubernetes_io_component=~\"${component}\"}[1m]) * 60) by(namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Logs - Avg per 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(rate({namespace=~\"${namespace}\", app_kubernetes_io_name=~\"${name}\", app_kubernetes_io_component=~\"${component}\"}[1m]) * 60) by(namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Logs - Max per 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(rate({namespace=~\"${namespace}\", app_kubernetes_io_name=~\"${name}\", app_kubernetes_io_component=~\"${component}\"}[1m]) * 60) by(namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  }
 ]
}