{
 "title": "loki-components-v2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "ns", "query": "monitoring" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total number of log messages created by Loki itself",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_internal_log_messages_total[2m]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(loki_internal_log_messages_total{level=\"error\"}[2m]))",
       "legendFormat": "Errors"
      },
      {
       "expr": "sum(rate(loki_internal_log_messages_total{level=\"warn\"}[2m]))",
       "legendFormat": "Warnings"
      }
     ]
    },
    {
     "title": "Number of received HTTP requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds[5m])) by(le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds[5m])) by(le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(loki_request_duration_seconds[5m])) by(le))",
       "legendFormat": "P90"
      }
     ]
    }
   ]
  },
  {
   "title": "Loki - Distributors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-distributor-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-distributor-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The total number of uncompressed bytes received per both tenant and retention hours",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_bytes_received_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of log entries received per tenant",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_lines_received_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of batch appends sent to ingesters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_appends_total[2m]) * 60)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The total number of failed batch appends sent to ingesters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(loki_distributor_ingester_append_failures_total[2m]))",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Loki - Ingesters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU time consumed in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-ingester-.*\", container!=\"\"}[2m])) by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current memory usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-ingester-.*\", container!=\"\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "The total number of chunks in memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_chunks)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "The total number of streams in memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_ingester_memory_streams)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total bytes stored in chunks per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunk_stored_bytes_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "The total number of streams created per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_created_total[2m]) * 60)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total stored chunks per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_stored_total[2m]) * 60)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "The total number of streams removed per tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_streams_removed_total[2m]) * 60)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "The total number of series pending in the flush queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(cortex_ingester_flush_queue_length)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "The total number of chunks created in the ingester",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(loki_ingester_chunks_created_total[2m]) * 60)",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Loki - Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU time consumed in seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-querier-.*\", container!=\"\"}[2m])) by(pod) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Current memory usage in bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-querier-.*\", container!=\"\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "The current number of clients connected to query-frontend",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_query_frontend_clients)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of active tailers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(loki_querier_tail_active)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Number of concurrent querier workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_worker_concurrency)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of active streams being tailed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_tail_active_streams)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of queries being processed by the querier workers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_worker_inflight_queries)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of active streams being tailed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(loki_querier_tail_bytes_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of index cache corruptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_index_cache_corruptions_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of index cache operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(loki_querier_index_cache_gets_total)",
     "legendFormat": "gets"
    },
    {
     "expr": "sum(loki_querier_index_cache_hits_total)",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(loki_querier_index_cache_puts_total)",
     "legendFormat": "puts"
    }
   ]
  },
  {
   "title": "Loki - Frontend",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU time consumed in seconds",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-frontend-.*\", container!=\"\"}[2m])) by(pod) > 0",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Current memory usage in bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"${ns}\", pod=~\".*-loki-distributed-query-frontend-.*\", container!=\"\"}) by(pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "The current number of queues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_query_frontend_enqueue_count)",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "The current number of shards",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(loki_query_frontend_shards_total)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Promtail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Number of bytes read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(promtail_read_bytes_total)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Number of bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_sent_bytes_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of bytes dropped because failed to be sent to the ingester after all retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_bytes_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of lines read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_read_lines_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of log entries dropped because failed to be sent to the ingester after all retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_dropped_entries_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of active files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(promtail_files_active_total)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of total failed targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_targets_failed_total[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Number of total active targets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(promtail_targets_active_total)",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}