{
 "title": "Nexus Infra",
 "description": "Nexus Dashboard by KL",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": {
     "query": "label_values(up{job=\"monitoring/nexus-monitor\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(jvm_vm_uptime{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Heap Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_usage{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "FileDescriptor Ratio",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_fd_usage{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Readonly Enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "expr": "sum(readonly_enabled{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Nexus Component",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "FileBlobStore",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "copy - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_copy_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "copy - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "deleteHard - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_deleteHard_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "deleteHard - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "get - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_get_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "get - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "delete - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_delete_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "delete - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "create - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_blobstore_file_FileBlobStore_create_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "create - p99"
    }
   ]
  },
  {
   "title": "RepositoryComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getBrowseableFormats - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_getBrowseableFormats_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getBrowseableFormats - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "readReferences - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_readReferences_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "readReferences - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_read_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_RepositoryComponent_read_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "UserComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_coreui_UserComponent_readSources_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "readSources - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_UserComponent_readSources_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "readSources - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_UserComponent_read_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_UserComponent_read_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "SecurityComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getPermissions - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_rapture_internal_security_SecurityComponent_getPermissions_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getPermissions - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getUser - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_rapture_internal_security_SecurityComponent_getUser_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "getUser - p99"
    }
   ]
  },
  {
   "title": "SearchComponent Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_coreui_SearchComponent_read_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_SearchComponent_read_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "BrowseComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_coreui_BrowseComponent_read_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_coreui_BrowseComponent_read_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "Component Exceptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_BlobStoreComponent_readGroups_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "BlobStoreComponent"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_blobstore_s3_internal_ui_S3Component_signertypes_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "S3Component"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_TaskComponent_update_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "TaskComponent"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_rapture_internal_state_StateComponent_getState_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "StateComponent"
    },
    {
     "expr": "sum(rate(\n    com_sonatype_nexus_migration_ui_AssistantComponent_cancel_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "AssistantComponent-Cancel"
    },
    {
     "expr": "sum(rate(\n    com_sonatype_nexus_migration_ui_AssistantComponent_abort_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "AssistantComponent-Abort"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_FreezeComponent_update_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "FreezeComponent-Update"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_FreezeComponent_read_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "FreezeComponent-Read"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_SelectorComponent_readReferences_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "SelectorComponent"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_RepositoryComponent_rebuildIndex_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "RepositoryComponent"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "LdapServerComponent"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_BrowseComponent_read_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "BrowseComponent"
    },
    {
     "expr": "sum(rate(\n    com_sonatype_nexus_clm_internal_ui_ClmComponent_readApplications_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "ClmComponent-Read"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_internal_capability_CapabilityComponent_remove_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "CapabilityComponent-Remove"
    },
    {
     "expr": "sum(rate(\n    com_sonatype_nexus_ssl_plugin_internal_ui_CertificateComponent_details_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "CertificateComponent-Details"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_SearchComponent_read_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "SearchComponent-Read"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_rapture_internal_security_SecurityComponent_authenticate_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "SecurityComponent-Authenticate"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_changeOrder_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "LdapServerComponent-ChangeOrder"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_coreui_RepositoryComponent_remove_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "RepositoryComponent-Remove"
    },
    {
     "expr": "sum(rate(\n    org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_readReferences_exceptions_total{namespace=~\"${ns}\"}[5m]\n))",
     "legendFormat": "LdapServerComponent-Read"
    }
   ]
  },
  {
   "title": "LdapServerComponent",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "verifyLogin - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_verifyLogin_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "verifyLogin - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_update_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "update - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_update_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "update - p99"
    },
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_read_timer{\n    quantile=\"0.5\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p50"
    },
    {
     "expr": "sum(org_sonatype_nexus_ldap_internal_ui_LdapServerComponent_read_timer{\n    quantile=\"0.99\",namespace=~\"${ns}\"\n})",
     "legendFormat": "read - p99"
    }
   ]
  },
  {
   "title": "Jetty WebAppContext",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jetty Responses Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_eclipse_jetty_webapp_WebAppContext_1xx_responses_total{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(rate(org_eclipse_jetty_webapp_WebAppContext_2xx_responses_total{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(org_eclipse_jetty_webapp_WebAppContext_5xx_responses_total{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(rate(org_eclipse_jetty_webapp_WebAppContext_4xx_responses_total{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(org_eclipse_jetty_webapp_WebAppContext_3xx_responses_total{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "3xx"
    }
   ]
  },
  {
   "title": "Jetty Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.5\",namespace=~\"${ns}\"})",
     "legendFormat": "p50"
    },
    {
     "expr": "sum(org_eclipse_jetty_webapp_WebAppContext_requests{quantile=\"0.99\",namespace=~\"${ns}\"})",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Jetty ThreadPool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(org_eclipse_jetty_util_thread_QueuedThreadPool_qtp1770819476_jobs{namespace=~\"${ns}\"})",
     "legendFormat": "wait-jobs"
    },
    {
     "expr": "sum(org_eclipse_jetty_util_thread_QueuedThreadPool_qtp2134194857_size{namespace=~\"${ns}\"})",
     "legendFormat": "current-size"
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Collections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_garbage_collectors_PS_MarkSweep_count{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "major GC(marksweep)"
    },
    {
     "expr": "sum(rate(jvm_garbage_collectors_PS_Scavenge_count{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "minor GC(scavenge)"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_garbage_collectors_PS_MarkSweep_time{namespace=~\"${ns}\"}[5m])) /\nsum(rate(jvm_garbage_collectors_PS_MarkSweep_count{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "major GC(marksweep)"
    },
    {
     "expr": "sum(rate(jvm_garbage_collectors_PS_Scavenge_time{namespace=~\"${ns}\"}[5m])) /\nsum(rate(jvm_garbage_collectors_PS_Scavenge_count{namespace=~\"${ns}\"}[5m]))",
     "legendFormat": "minor GC(scavenge)"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_heap_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_heap_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_heap_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_non_heap_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_non_heap_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_non_heap_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_total_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_total_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_total_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap) ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PS Eden Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_PS_Eden_Space_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Eden_Space_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Eden_Space_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "PS Survivor Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_PS_Survivor_Space_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Survivor_Space_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Survivor_Space_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "PS Old Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_PS_Old_Gen_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Old_Gen_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_PS_Old_Gen_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Metaspace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_Metaspace_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_Metaspace_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_Metaspace_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Compressed Class Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_Compressed_Class_Space_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_Compressed_Class_Space_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_Compressed_Class_Space_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "Code Cache",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_pools_Code_Cache_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_pools_Code_Cache_max{namespace=~\"${ns}\"})",
     "legendFormat": "max"
    },
    {
     "expr": "sum(jvm_memory_pools_Code_Cache_committed{namespace=~\"${ns}\"})",
     "legendFormat": "committed"
    }
   ]
  },
  {
   "title": "JVM Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffers_direct_count{namespace=~\"${ns}\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffers_direct_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_buffers_direct_capacity{namespace=~\"${ns}\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffers_mapped_count{namespace=~\"${ns}\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_buffers_mapped_used{namespace=~\"${ns}\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_buffers_mapped_capacity{namespace=~\"${ns}\"})",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_thread_states_daemon_count{namespace=~\"${ns}\"})",
     "legendFormat": "daemon"
    },
    {
     "expr": "sum(jvm_thread_states_terminated_count{namespace=~\"${ns}\"})",
     "legendFormat": "terminated"
    },
    {
     "expr": "sum(jvm_thread_states_count{namespace=~\"${ns}\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_thread_states_new_count{namespace=~\"${ns}\"})",
     "legendFormat": "new"
    },
    {
     "expr": "sum(jvm_thread_states_runnable_count{namespace=~\"${ns}\"})",
     "legendFormat": "runnable"
    },
    {
     "expr": "sum(jvm_thread_states_blocked_count{namespace=~\"${ns}\"})",
     "legendFormat": "blocked"
    },
    {
     "expr": "sum(jvm_thread_states_deadlock_count{namespace=~\"${ns}\"})",
     "legendFormat": "deadlock"
    },
    {
     "expr": "sum(jvm_thread_states_timed_waiting_count{namespace=~\"${ns}\"})",
     "legendFormat": "timed_waiting"
    },
    {
     "expr": "sum(jvm_thread_states_waiting_count{namespace=~\"${ns}\"})",
     "legendFormat": "waiting"
    }
   ]
  }
 ]
}