# https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/argocd/embedded-exporter.yml
apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "argocd-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "argocd.rules"
      rules:
        - alert: "ArgocdServiceNotSynced"
          expr: 'argocd_app_info{sync_status!="Synced", name!=""} != 0'
          for: "15m"
          labels:
            severity: "warning"
          annotations:
            summary: "ArgoCD service not synced (instance {{ $labels.instance }})"
            description: "Service {{ $labels.project }}/{{ $labels.name }} run by ArgoCD is currently not in sync!"

        - alert: "ArgocdServiceUnhealthy"
          expr: 'argocd_app_info{health_status!~"Healthy|Progressing", name!=""} != 0'
          for: "15m"
          labels:
            severity: "warning"
          annotations:
            summary: "ArgoCD service unhealthy (instance {{ $labels.instance }})"
            description: "Service {{ $labels.project }}/{{ $labels.name }} run by ArgoCD is currently not healthy!"

        - alert: "ArgocdAppAutoSyncDisabled"
          expr: 'argocd_app_info{autosync_enabled!="true", name!=""} > 0'
          for: "1h"
          labels:
            severity: "warning"
          annotations:
            summary: "ArgoCD service has auto-sync disabled (instance {{ $labels.instance }})"
            description: "Service {{ $labels.project }}/{{ $labels.name }} has auto-sync disabled!"

        - alert: "ArgocdAppSyncFailed"
          expr: 'round(increase(argocd_app_sync_total{phase!="Succeeded", name!=""}[10m])) > 0'
          for: "5m"
          labels:
            severity: "warning"
          annotations:
            summary: "ArgoCD service has failed to sync (instance {{ $labels.instance }})"
            description: "Service {{ $labels.project }}/{{ $labels.name }} has failed to sync with the status {{ $labels.phase }} the past 10m."

        - alert: "ArgocdNotificationDeliveryFailed"
          expr: 'round(increase(argocd_notifications_deliveries_total{succeeded!="true"}[10m])) > 0'
          for: "5m"
          labels:
            severity: "warning"
          annotations:
            summary: "ArgoCD notification delivery failed (instance {{ $labels.instance }})"
            description: "The notification job {{ $labels.job }} has failed to deliver to {{ $labels.service }} for the past 10m."
