apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "custom-pod-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "custom-pod-record.rules"
      rules:
        - expr: 'sum(kube_pod_info * on(namespace, pod) group_left kube_pod_created) by(node, namespace, pod)'
          record: "custom_pod_info"

    - name: "custom-pod-alert.rules"
      rules:
        - alert: "KubePodOomKilled"
          expr: |
            increase(kube_pod_container_status_restarts_total[5m]) *
            on (namespace, pod) group_left kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} > 0
          for: "1m"
          labels:
            severity: "warning"
          annotations:
            summary: "The {{ $labels.namespace }}/{{ $labels.pod }} terminated with OOMKilled reason."
            description: "The {{ $labels.namespace }}/{{ $labels.pod }} terminated on {{ $labels.node }}"
            runbook_url: ""
