apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "custom-storage-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "custom-k8s-alert.rules"
      rules:
        - alert: "KubePersistentVolumeAvailableSpace"
          expr: |
            sum(
              (kubelet_volume_stats_available_bytes * 100) / kubelet_volume_stats_capacity_bytes
            ) by(namespace, node, persistentvolumeclaim) < 50
          for: "1m"
          labels:
            severity: "warning"
          annotations:
            summary: "The {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} has less than 50% of available space."
            description: "The {{ $labels.namespace }}/{{ $labels.persistentvolumeclaim }} has less than 50% of available space."
            runbook_url: ""
