apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "custom-pod-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "custom-pod-record.rules"
      rules:
        - expr: 'sum(kube_pod_info * on(namespace, pod) group_left kube_pod_created) by(node, namespace, pod)'
          record: "custom_pod_info"

    # - name: "custom-pod-alert.rules"
    #   rules: []
