apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "karpenter-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "karpenter.rules"
      rules:
        - alert: "KarpenterCanNotRegisterNewNodes"
          expr: |
            (sum(karpenter_nodeclaims_launched) by(nodepool) - sum(karpenter_nodeclaims_registered) by(nodepool)) != 0
          for: "15m"
          labels:
            severity: "warning"
          annotations:
            summary: "Problem with registering new nodes in the cluster."
            description: |
              Karpenter in the nodepool `{{ $labels.nodepool }}` launched new nodes, but some of nodes did not registerd in the cluster during 15 min.
            runbook_url: "https://karpenter.sh/v0.37/reference/metrics/#nodeclaims-metrics"

        - alert: "KarpenterNodepoolAlmostFull"
          expr: |
            floor((sum(karpenter_nodepool_usage) by(nodepool, resource_type) / sum(karpenter_nodepool_limit) by(nodepool, resource_type)) * 100) > 80
          for: "15m"
          labels:
            severity: "warning"
          annotations:
            summary: "Nodepool almost full, you should increase limits."
            description: |
              Nodepool `{{ $labels.nodepool }}` launched `{{ $value }}%` `{{ $labels.resource_type }}` resources of the limit.
            runbook_url: "https://karpenter.sh/v0.37/reference/metrics/#nodeclaims-metrics"

        - alert: "KarpenterCloudproviderErrors"
          expr: 'increase(karpenter_cloudprovider_errors_total[10m]) > 0'
          for: "1m"
          labels:
            severity: "warning"
          annotations:
            summary: "Karpenter received an {{ $labels.error }} during an api call to the cloud provider."
            description: "Karpenter received an {{ $labels.error }} during an api call to the cloud provider."
            runbook_url: "https://karpenter.sh/v0.37/reference/metrics/#cloudprovider-metrics"
