apiVersion: "monitoring.coreos.com/v1"
kind: "PrometheusRule"
metadata:
  name: "promtail-rules"
  namespace: "monitoring"
  labels:
    release: "prom-operator"
spec:
  groups:
    - name: "promtail-alert.rules"
      rules:
        - alert: "PromtailRequestsErrors"
          expr: '100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[5m])) by(namespace, pod, route) / sum(rate(promtail_request_duration_seconds_count[5m])) by(namespace, pod, route) > 10'
          for: "15m"
          labels:
            severity: "critical"
          annotations:
            summary: "Promtail request errors (instance {{ $labels.namespace }}/{{ $labels.pod }})"
            description: "The {{ $labels.namespace }}/{{ $labels.pod }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}% errors."
            runbook_url: ""

        - alert: "PromtailRequestLatency"
          expr: 'histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m])) by(namespace, pod, route, le)) > 1'
          for: "15m"
          labels:
            severity: "critical"
          annotations:
            summary: "Promtail request latency (instance {{ $labels.namespace }}/{{ $labels.pod }})"
            description: "The {{ $labels.namespace }}/{{ $labels.pod }} {{ $labels.route }} is experiencing {{ printf \"%.2f\" $value }}s 99th percentile latency."
            runbook_url: ""
